version: '3'
services:
  postgres-order:
    container_name: postgres-order
    image: postgres:14.9-alpine
    environment:
      POSTGRES_DB: order_service
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    networks:
      - internal-network
    restart: always

  postgres-payment:
    container_name: postgres-payment
    image: postgres:14.9-alpine
    environment:
      POSTGRES_DB: payment_service
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - "5435:5432"
    expose:
      - "5435"
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data
    networks:
      - internal-network
    restart: always

  postgres-user:
    container_name: postgres-user
    image: postgres:14.9-alpine
    environment:
      POSTGRES_DB: user_service
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - "5436:5432"
    expose:
      - "5436"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - internal-network
    restart: always

  postgres-product:
    container_name: postgres-product
    image: postgres:14.9-alpine
    environment:
      POSTGRES_DB: product_service
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-product-data:/var/lib/postgresql/data
    networks:
      - internal-network
    restart: always

  postgres-inventory:
    container_name: postgres-inventory
    image: postgres:14.9-alpine
    environment:
      POSTGRES_DB: inventory_service
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-inventory-data:/var/lib/postgresql/data
    networks:
      - internal-network
    restart: always

  zipkin:
    image: openzipkin/zipkin:2.24.3
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - internal-network

  #  keycloak:
  #    image: quay.io/keycloak/keycloak:22.0.1
  #    container_name: keycloak
  #    command: [ "start-dev", "--import-realm" ]
  #    environment:
  #      KEYCLOAK_ADMIN: admin
  #      KEYCLOAK_ADMIN_PASSWORD: admin
  #    ports:
  #      - "8080:8080"
  #    volumes:
  #      - ./realms/:/opt/keycloak/data/import/

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - internal-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - internal-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

#  activemq:
#    image: apache/activemq-artemis:2.31.2-alpine
#    ports:
#      - "8161:8161"
#      - "61616:61616"
#      - "5672:5672"
#    networks:
#      - internal-network
#    environment:
#      ARTEMIS_USER: myuser
#      ARTEMIS_PASSWORD: mypassword
#    volumes:
#      - activemq-data:/var/lib/activemq/data

  activemq:
    image: symptoma/activemq:5.15.13
    container_name: activemq
    ports:
      - "8161:8161" # Web Console
      - "61616:61616" # OpenWire
      - "5672:5672" # AMQP
      - "61613:61613" # STOMP
      - "1883:1883"   # MQTT
    networks:
      - internal-network
    environment:
      ACTIVEMQ_USERNAME: system
      ACTIVEMQ_PASSWORD: manager
      ACTIVEMQ_WEBADMIN_USERNAME: admin
      ACTIVEMQ_WEBADMIN_PASSWORD: admin
    volumes:
      - activemq-data:/data/activemq
      - activemq-log:/var/log/activemq

networks:
  internal-network:

volumes:
  postgres-product-data:
  postgres-order-data:
  postgres-payment-data:
  postgres-user-data:
  postgres-inventory-data:
  activemq-data:
  activemq-log: